In [2]:
import numpy as np
from sklearn.preprocessing import Imputer

In [3]:
X = [
    [2, 2, 4, 1],
    [np.nan, 3, 4, 4],
    [1, 1, 1, np.nan],
    [2, 2, np.nan, 3]
]
X2 = [
    [2, 6, np.nan, 1],
    [np.nan, 5, np.nan, 1],
    [4, 1, np.nan, 5],
    [np.nan, np.nan, np.nan, 1]
]

In [4]:
# 按照列进行填充值的计算
imp1 = Imputer(missing_values='NaN', strategy='mean', axis=0)
# 按照行计算填充值（如果按照行进行填充的话，那么是不需要进行模型fit的，直接使用X的现有的行信息进行填充的）-- 一般不用
imp2 = Imputer(missing_values='NaN', strategy='mean', axis=1)

imp1.fit(X)
imp2.fit(X)

print("按照列填充策略：", imp1.statistics_)

按照列填充策略： [1.66666667 2.         3.         2.66666667]


In [5]:
print (imp1.transform(X2))
print ("--------------------------")
print (imp2.transform(X2))

[[2.         6.         3.         1.        ]
 [1.66666667 5.         3.         1.        ]
 [4.         1.         3.         5.        ]
 [1.66666667 2.         3.         1.        ]]
--------------------------
[[2.         6.         3.         1.        ]
 [3.         5.         3.         1.        ]
 [4.         1.         3.33333333 5.        ]
 [1.         1.         1.         1.        ]]


In [6]:
imp1 = Imputer(missing_values='NaN', strategy='mean', axis=0)
imp2 = Imputer(missing_values='NaN', strategy='median', axis=0)
imp3 = Imputer(missing_values='NaN', strategy='most_frequent', axis=0)
imp1.fit(X)
imp2.fit(X)
imp3.fit(X)

Imputer(axis=0, copy=True, missing_values='NaN', strategy='most_frequent',
    verbose=0)

In [7]:
print ("--------------------------")
print (imp1.transform(X2))
print ("--------------------------")
print (imp2.transform(X2))
print ("--------------------------")
print (imp3.transform(X2))

--------------------------
[[2.         6.         3.         1.        ]
 [1.66666667 5.         3.         1.        ]
 [4.         1.         3.         5.        ]
 [1.66666667 2.         3.         1.        ]]
--------------------------
[[2. 6. 4. 1.]
 [2. 5. 4. 1.]
 [4. 1. 4. 5.]
 [2. 2. 4. 1.]]
--------------------------
[[2. 6. 4. 1.]
 [2. 5. 4. 1.]
 [4. 1. 4. 5.]
 [2. 2. 4. 1.]]
