In [2]:
import numpy as np

from sklearn.preprocessing import OneHotEncoder
from sklearn.feature_extraction import DictVectorizer

In [3]:
# OneHotEncoder要求数据类别必须是数值的
enc = OneHotEncoder()
a = np.array([[0, 0, 3], [1, 1, 0], [0, 2, 1], [1, 0, 2], [1, 1, 1]])
enc.fit(a) 
print(a)
print("编码结果",enc.n_values_)

[[0 0 3]
 [1 1 0]
 [0 2 1]
 [1 0 2]
 [1 1 1]]
编码结果 [2 3 4]


In [4]:
enc.transform([[0, 1, 2]]).toarray()

array([[1., 0., 0., 1., 0., 0., 0., 1., 0.]])

In [5]:
# sparse：最终产生的结果是否是稀疏化矩阵，默认为True，一般不改动
dv = DictVectorizer(sparse=False)
D = [{'foo':1, 'bar':2.2}, {'foo':3, 'baz': 2}]
X = dv.fit_transform(D)
print("D的转化结果：\n", X)
# 直接把字典中的key作为特征，value作为特征值，然后构建特征矩阵
print ("特征：", dv.get_feature_names())
print ("{'foo':4, 'unseen':3}转换结果:\n", dv.transform({'foo':4, 'unseen':3}))

D的转化结果：
 [[2.2 0.  1. ]
 [0.  2.  3. ]]
特征： ['bar', 'baz', 'foo']
{'foo':4, 'unseen':3}转换结果:
 [[0. 0. 4.]]


In [6]:
from sklearn.feature_extraction import FeatureHasher

h = FeatureHasher(n_features=3)
D = [{'dog': 1, 'cat':2, 'elephant':4},{'dog': 2, 'run': 5}]
# 直接以hash值计算结果 -- 该方式一般不用
f = h.transform(D)
f.toarray()

array([[-1.,  2., -4.],
       [-2., -5.,  0.]])